[PHP]
extension_dir="C:\Users\india\AppData\Roaming\Local\lightning-services\php-8.2.29+0\bin\win64\ext"
extension=php_mysqli.dll
extension=php_pdo_mysql.dll
extension=php_curl.dll
extension=php_openssl.dll
extension=php_mbstring.dll
extension=php_gd.dll
extension=php_zip.dll
extension=php_exif.dll
extension=php_fileinfo.dll
extension=php_sqlite3.dll
extension=php_pdo_sqlite.dll

[MySQLi]
mysqli.default_host = localhost
mysqli.default_port = 10005
mysqli.default_user = root
mysqli.default_pw = root

[Pdo_Mysql]
pdo_mysql.default_host = localhost
pdo_mysql.default_port = 10005
pdo_mysql.default_user = root
pdo_mysql.default_pw = root

error_reporting = E_ALL & ~E_DEPRECATED
display_errors = On
log_errors = On
memory_limit = 512M
max_execution_time = 300
